spring.application.name=farmaconecta

# Importa as variaveis do arquivo .env na raiz do projeto
spring.config.import=optional:file:./.env[.properties]

# PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/farmaconecta
spring.datasource.username=farmaconecta
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://127.0.0.1:5433/farmaconecta
spring.flyway.user=farmaconecta
spring.flyway.password=${POSTGRES_PASSWORD}

# Servidor
server.port=8081